// ===========================================
// js/data.js - Datos (conjuntos de caracteres y listas de palabras)
// ===========================================

// Conjuntos de caracteres base para contraseñas regulares.
export const baseCharSets = {
    uppercase: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    lowercase: "abcdefghijklmnopqrstuvwxyz",
    numbers: "0123456789",
    symbols: "!@#$%^&*()_+-=[]{}|;:,.<>/?",
};

// Caracteres que pueden confundirse fácilmente en contraseñas (L minúscula, 1, O mayúscula, 0).
export const ambiguousChars = /[l1O0]/g;

// Lista EXTENSA de palabras en español para passphrases (generación aleatoria pura).
export const wordListES = [
    "abaco", "abandono", "abeja", "abierto", "absoluto", "abuelo", "abundancia", "acabar", "academico", "acceso",
    "accion", "aceite", "acelerar", "acento", "aceptar", "acero", "acertar", "acido", "aclarar", "acoger",
    "aconsejar", "acordar", "acostado", "acostumbre", "acre", "acto", "actuacion", "actual", "acuerdo", "acumular",
    "adaptar", "adelante", "adelgazar", "adentro", "adhesion", "adicion", "adivinar", "adjunto", "administrar", "admirable",
    "admirar", "admision", "adolescente", "adoptar", "adorar", "adorno", "adquirir", "advertir", "aereo", "aeropuerto",
    "afectar", "aficion", "afirmar", "afligido", "aflojar", "afuera", "agarrar", "agencia", "agenda", "agente",
    "agil", "agitado", "agitar", "agoniza", "agosto", "agotado", "agradable", "agradecer", "agresivo", "agricultura",
    "agrio", "agua", "aguila", "agujero", "ahi", "ahogar", "ahora", "ahorrar", "aire", "aislado",
    "ajeno", "ajustar", "ala", "alambre", "alargar", "alarma", "album", "alcanzar", "alcohol", "aldea",
    "alegrar", "alegre", "alegria", "alejar", "aleman", "alerta", "alfabeto", "alfombra", "algo", "algodon",
    "alguien", "alguno", "alhaja", "alianza", "aliento", "alimento", "alinear", "alisar", "allanar", "alli",
    "alma", "almacen", "almohada", "almuerzo", "alto", "altura", "alumbrado", "alumno", "alza", "amable",
    "amapola", "amar", "amargo", "amarillo", "ambiente", "ambito", "ambulancia", "amenaza", "america", "amigo",
    "amistad", "amo", "amonestar", "amortiguar", "amplio", "ampolla", "ancho", "anciano", "andaluz", "andar",
    "anillo", "anima", "animal", "animar", "animo", "aniversario", "ano", "anotar", "ansiado", "anterior",
    "anticipo", "antiguedad", "antojo", "anual", "anunciar", "anuncio", "anzuelo", "añadir", "añejo", "año",
    "apagar", "aparato", "aparecer", "aparente", "apartamento", "aparte", "apenas", "aplaudir", "aplicar", "apoyar",
    "aprender", "apretar", "aprovechar", "aproximar", "apuesta", "apuntar", "aquel", "aqui", "arabe", "araña",
    "arbol", "arcilla", "arco", "arder", "ardilla", "arena", "arma", "armario", "arquitecto", "arrancar",
    "arrastrar", "arreglar", "arriba", "arrojar", "arrugado", "arroz", "arte", "articulo", "artista", "asar",
    "ascensor", "asegurar", "asesino", "asiento", "asistir", "asociacion", "asombro", "aspecto", "aspera", "aspiracion",
    "asunto", "ataque", "atender", "atento", "atmosfera", "atras", "atreverse", "atun", "aumentar", "aun",
    "aunque", "auto", "autor", "autoridad", "auxilio", "avance", "avanzar", "ave", "avenida", "aventura",
    "averiguar", "avion", "avisar", "ayer", "ayuda", "ayudar", "ayuntamiento", "azucar", "azul", "baba",
    "bailar", "bailarin", "baile", "bajar", "baja", "bajo", "balanza", "balcon", "bala", "ballena",
    "balon", "bambú", "banco", "banda", "bandeja", "bandera", "bandido", "bañarse", "barato", "barba",
    "barco", "barrer", "barrio", "base", "basura", "batalla", "bateria", "baul", "bebe", "beber",
    "bebida", "bello", "beneficio", "besar", "biblioteca", "bicicleta", "bien", "billete", "biologia", "blanco",
    "blando", "bloquear", "boca", "bola", "boleto", "bolsa", "bombero", "bondad", "bonito", "bordo",
    "borrar", "bosque", "bote", "botella", "boton", "brazo", "breve", "brillar", "brillo", "brisa",
    "bromear", "bronca", "bueno", "bulto", "burbuja", "burro", "buscar", "busto", "cabalgar", "caballero",
    "caballo", "cabeza", "cabina", "cabo", "cada", "cadena", "caer", "cafe", "caida", "caja",
    "calabaza", "calcio", "calcular", "caldera", "calido", "caliente", "calificar", "calle", "cama", "camarero",
    "cambio", "caminar", "camino", "camion", "campana", "campo", "canal", "canasta", "cancelar", "cancer",
    "cancion", "canela", "cantar", "cantidad", "canto", "caña", "caoba", "capacidad", "capital", "capitan",
    "capturar", "caracter", "cara", "carbon", "carcel", "cargador", "cargar", "caricia", "caridad", "cariño",
    "carne", "carpintero", "carrera", "carro", "carta", "cartera", "casa", "casar", "casi", "caso",
    "castigar", "catastrofe", "catedral", "categoria", "causa", "caza", "cazar", "cebolla", "ceder", "celda",
    "celebrar", "celeste", "cena", "ceniza", "centro", "cepillo", "cerca", "cerebro", "cereza", "cero",
    "cerrar", "cerro", "cesar", "cesta", "cielo", "cien", "ciencia", "cierto", "cifrar", "cigarrillo",
    "cima", "cinco", "cine", "cinta", "cintura", "circulo", "ciudad", "civil", "claro", "clase",
    "clavar", "cliente", "clima", "clinica", "coche", "cocina", "cocinar", "codigo", "codo", "coger",
    "cola", "colgar", "colina", "color", "columna", "comandar", "combate", "combinar", "combustible", "comedia",
    "comenzar", "comer", "comercio", "comida", "comisaria", "comision", "como", "comodo", "comparar", "compasion",
    "compatible", "competencia", "completar", "completo", "complicado", "componer", "comprar", "comprender", "comprimir", "compromiso",
    "comun", "comunicar", "conciencia", "concluir", "condicion", "conducir", "conferencia", "confesar", "confiar", "confirmar",
    "confuso", "congelar", "conocer", "conquista", "conseguir", "consejo", "consentir", "conservar", "considerar", "consistencia",
    "consolar", "constante", "construir", "consultar", "consumir", "contacto", "contar", "contener", "contento", "contestar",
    "continuar", "contra", "contrato", "control", "convalecencia", "convencer", "conversar", "convertir", "copa", "copia",
    "copiar", "corazon", "coro", "corona", "corte", "cortar", "cosa", "cosechar", "costa", "costar",
    "costumbre", "crear", "crecer", "creer", "crimen", "cristal", "cruz", "cuaderno", "cuadro", "cual",
    "cuando", "cuanto", "cuarto", "cuatro", "cubrir", "cuchara", "cuchillo", "cuello", "cuenta", "cuento",
    "cuerpo", "cuestion", "cuidado", "cuidar", "culpa", "cultura", "cumplir", "curar", "curioso", "curso",
    "curva", "custodia", "cutis", "dama", "danza", "daño", "dar", "dato", "deber", "decidir",
    "decir", "dedo", "defender", "defensa", "definitivo", "dejar", "delgado", "delito", "demasiado", "demostrar",
    "denunciar", "depender", "deporte", "deposito", "derecho", "derribar", "desaparecer", "desarrollo", "desayuno", "descansar",
    "descargar", "desconocido", "descubrir", "desde", "desear", "deseo", "desesperar", "desierto", "designar", "desliz",
    "despacio", "despertar", "despues", "destino", "destruir", "detalle", "detener", "determinar", "deuda", "dia",
    "diablo", "dialogo", "diamante", "diario", "dibujar", "diente", "diez", "diferencia", "dificil", "digitar",
    "digno", "dinero", "direccion", "directo", "dirigir", "discutir", "diseñar", "disfrutar", "disponer", "distancia",
    "distinto", "divertir", "dividir", "doble", "doctor", "doce", "documento", "dolar", "doler", "domingo",
    "donde", "dormir", "dos", "doce", "drama", "ducha", "duda", "dulce", "duro", "echar",
    "edad", "edificio", "educar", "efecto", "eficaz", "ejecutar", "ejemplo", "ejercicio", "eleccion", "electrico",
    "elegir", "elemento", "elevar", "eliminar", "ella", "ello", "emocion", "emperador", "emplear", "empleado",
    "empresa", "empujar", "encontrar", "energico", "energia", "enfrentar", "enfermedad", "enfermo", "engañar", "enorme",
    "enseñar", "entender", "entero", "enterrar", "entrada", "entrar", "entregar", "entrevista", "entusiasmo", "enviar",
    "epidemia", "equipo", "error", "escalera", "escenario", "escribir", "escritor", "escuchar", "escuela", "esfuerzo",
    "espacio", "espada", "español", "especial", "especie", "esperar", "espeso", "esposa", "esquina", "estable",
    "establecer", "estacion", "estado", "estadounidense", "estanque", "estar", "estatua", "este", "estrella", "estructura",
    "estudiante", "estudiar", "etapa", "eterno", "evento", "evitar", "exacto", "examinar", "excesivo", "existencia",
    "existir", "exito", "experiencia", "explicar", "exponer", "expresar", "extraño", "extremo", "fabrica", "facil",
    "factura", "familia", "famoso", "fantasia", "fantasma", "favor", "febrero", "fecha", "felicidad", "feliz",
    "fenomeno", "feo", "feria", "fiesta", "figura", "fijo", "fila", "filosofia", "fin", "final",
    "firma", "firmar", "fisico", "flaco", "flecha", "flor", "flotar", "fluido", "fondo", "forma",
    "formar", "formula", "fortaleza", "foto", "frances", "frase", "frecuencia", "frente", "fresco", "frio",
    "fruta", "fuego", "fuerza", "funcion", "fundamento", "futuro", "galeria", "ganar", "gancho", "garganta",
    "gasolina", "gastar", "gato", "gemelo", "general", "genero", "gente", "gesto", "gigante", "girar",
    "globo", "gloria", "gobernar", "gobierno", "golpe", "gordo", "gota", "gracia", "grado", "gran",
    "grande", "grano", "gratis", "grave", "gritar", "grueso", "grupo", "guardar", "guapo", "guerra",
    "guia", "guitarra", "gustar", "haber", "habitacion", "habitante", "hablar", "hacer", "hacia", "hallar",
    "hambre", "harina", "hasta", "hecho", "helado", "helicoptero", "herida", "hermano", "hermoso", "heroe",
    "herramienta", "hielo", "hierro", "hijo", "historia", "hogar", "hoja", "hombre", "hombro", "honor",
    "hora", "horizonte", "hormiga", "hospital", "hotel", "hoy", "hueso", "humano", "humedo", "humor",
    "ida", "idea", "ideal", "idioma", "iglesia", "ignorar", "igual", "ilegal", "ilustracion", "imagen",
    "imaginar", "impedir", "imperio", "implicar", "importancia", "importante", "imposible", "impresion", "impuesto", "incluir",
    "incluso", "indicar", "individuo", "industrial", "infancia", "inferior", "infinito", "influencia", "informacion", "informar",
    "ingeniero", "ingreso", "inicial", "iniciar", "inmediato", "inmigrante", "inocente", "insecto", "inspirar", "instante",
    "instrumento", "inteligente", "intencion", "interesar", "interesante", "interior", "internacional", "interpretar", "interrumpir", "intervalo",
    "introducir", "inutil", "invierno", "invitar", "ir", "isla", "izquierda", "jabón", "jamón", "jardín",
    "jarra", "jefe", "joven", "joya", "juego", "jugar", "juicio", "junio", "junto", "juramento",
    "justicia", "justo", "juventud", "labor", "lado", "ladron", "lagrima", "lamentar", "lampara", "lana",
    "lapiz", "largo", "lastima", "lavar", "lazo", "leche", "leer", "legal", "lejano", "lengua",
    "lento", "leon", "levantar", "leve", "ley", "libertad", "libreria", "libro", "ligero", "limitar",
    "limite", "limpio", "linea", "lingüistico", "liquido", "lista", "listo", "literatura", "litro", "llamar",
    "llave", "llegar", "llenar", "llevar", "llorar", "lluvia", "local", "loco", "lograr", "lomo",
    "luz", "madera", "madre", "maduro", "maestro", "magia", "magnifico", "maiz", "maleta", "malo",
    "mamá", "mancha", "mandar", "manejar", "manera", "mano", "mantener", "manta", "mañana", "mapa",
    "maquina", "mar", "maravilloso", "marca", "marcha", "margen", "marido", "masa", "masaje", "matar",
    "material", "matrimonio", "maximo", "mayor", "mayoria", "mecanismo", "medida", "medio", "medir", "mejor",
    "mejora", "melon", "memoria", "mencionar", "menor", "menos", "mensaje", "mente", "mentira", "mercado",
    "merecer", "mesa", "meta", "meter", "metro", "mezclar", "miedo", "miembro", "mientras", "miercoles",
    "milagro", "militar", "mina", "mineral", "minimo", "ministro", "minuto", "mio", "mirar", "misa",
    "miserable", "misterio", "mitad", "modelo", "moderno", "modo", "mojar", "molestar", "molecula", "momento",
    "moneda", "mono", "monstruo", "montaña", "montar", "morir", "mostrar", "motivo", "mover", "movimiento",
    "mucho", "mueble", "muerte", "mujer", "mundo", "musica", "nacer", "nacional", "nada", "nadie",
    "naranja", "nariz", "naturaleza", "navegar", "navidad", "necesitar", "negocio", "negro", "nervioso", "neto",
    "nevar", "nido", "ninguno", "niño", "nivel", "no", "noble", "noche", "nombre", "normal",
    "norte", "noticia", "novela", "noviembre", "nube", "nuestro", "nuevo", "numero", "nunca", "nutricion",
    "obedecer", "objeto", "obligar", "obra", "observar", "obtener", "ocasion", "ocultar", "ocupar", "ocurrir",
    "oceano", "octubre", "odiar", "oeste", "ofender", "ofrecer", "oido", "ojo", "ola", "oler",
    "olvidar", "once", "operacion", "opinion", "oponer", "oportunidad", "optar", "orden", "ordenar", "oreja",
    "organismo", "organizar", "origen", "oro", "oscuro", "otoño", "otro", "oveja", "paciencia", "pacifico",
    "padre", "pagar", "pagina", "pais", "paja", "palabra", "palido", "palma", "palpitar", "pan",
    "panal", "pantalla", "pañuelo", "papel", "par", "parar", "parecer", "pared", "pareja", "parque",
    "parte", "participar", "particular", "partido", "pasado", "pasaje", "pasar", "pasillo", "paso", "pasta",
    "paz", "pecho", "pedir", "pegar", "pelear", "pelicula", "pelo", "peligro", "pena", "penal",
    "pensar", "peor", "pequeño", "pera", "percibir", "perder", "perdonar", "perfecto", "perfume", "periodico",
    "permitir", "pero", "perro", "perseguir", "persona", "personal", "pesar", "pescado", "peso", "pestaña",
    "picante", "pie", "piedra", "piel", "pierna", "pieza", "piloto", "pincel", "pintar", "pintura",
    "piso", "pistola", "pizarra", "placer", "plan", "planeta", "planta", "plata", "plato", "playa",
    "plaza", "poblacion", "pobre", "poco", "poder", "podrir", "poema", "poeta", "politica", "polvo",
    "poner", "popular", "porcentaje", "portal", "posible", "posicion", "practica", "precio", "precisar", "preferir",
    "pregunta", "preguntar", "premio", "preocupar", "preparar", "presentar", "presidente", "presion", "prestar", "primer",
    "principio", "prision", "privado", "problema", "proceder", "proceso", "producir", "producto", "profesion", "profesor",
    "profundo", "programa", "progresar", "prohibir", "prometer", "promover", "pronto", "propiedad", "propio", "proponer",
    "proteger", "proteina", "protestar", "proveer", "proximo", "prueba", "publico", "pueblo", "puerta", "puerto",
    "puesto", "pulmon", "pulsera", "punto", "purpura", "quedar", "quemar", "querer", "queso", "quien",
    "quieto", "quimica", "quince", "quitar", "radio", "raiz", "rama", "rapido", "raro", "raton",
    "razon", "real", "realizar", "rebaño", "rebelde", "recibir", "reciente", "recoger", "reconocer", "recordar",
    "recto", "recuerdo", "redondo", "referir", "reflejar", "refrigerador", "regalo", "regresar", "regular", "reina",
    "reino", "reir", "relacion", "relativo", "reloj", "remoto", "rendir", "renta", "reparar", "repasar",
    "repetir", "reportaje", "representar", "reservar", "residencia", "resistir", "resolver", "respetar", "respirar", "responder",
    "responsable", "restaurante", "resultado", "reunion", "revelar", "revista", "rey", "rezar", "rico", "riesgo",
    "rigido", "rincon", "rio", "riqueza", "risa", "robot", "rojo", "romper", "ropa", "rosa",
    "rotura", "rubio", "rueda", "ruido", "ruta", "saber", "sabio", "sacar", "sacerdote", "sacrificio",
    "sala", "salida", "salir", "salmon", "salto", "salud", "saludar", "salvar", "sangre", "santa",
    "santo", "sapo", "satisfacer", "secar", "seco", "secreto", "seccion", "sed", "seguir", "segundo",
    "seguro", "seis", "seleccion", "semana", "semilla", "sendero", "sensacion", "sensible", "sentar", "sentido",
    "sentir", "separar", "septiembre", "ser", "serie", "serio", "servicio", "servir", "sesion", "setenta",
    "sexo", "sexto", "siempre", "siete", "siglo", "significar", "siguiente", "silencio", "silla", "simbolo",
    "simple", "simular", "sincero", "sindicato", "sino", "sistema", "sitio", "situacion", "social", "sociedad",
    "sol", "solicitar", "solo", "solucion", "sombra", "sombrero", "sonar", "sonido", "sonreir", "sonrisa",
    "sopa", "sordo", "sorpresa", "sostener", "suave", "subir", "sucio", "suelo", "suerte", "suficiente",
    "sugerir", "suicida", "suizo", "sumar", "superficie", "superior", "suponer", "surgir", "sur", "suspirar",
    "sustancia", "taco", "tacto", "talento", "taller", "tamaño", "tambien", "tan", "tanto", "tapa",
    "tapete", "tarde", "tarea", "tarjeta", "taxi", "taza", "techo", "tejer", "telefono", "tema",
    "temblar", "temprano", "tendencia", "tener", "teoria", "tercero", "terminar", "terrible", "terror", "tesoro",
    "testigo", "texto", "tia", "tiempo", "tienda", "tierra", "tigre", "timbre", "tina", "tinta",
    "tio", "tipo", "tirar", "tocar", "todavia", "todo", "tomar", "tono", "tonto", "tocar",
    "tormenta", "tornillo", "torre", "tortuga", "total", "trabajar", "trabajo", "tradicion", "trafico", "traje",
    "tranquilo", "transformar", "transporte", "tratar", "tren", "trece", "treinta", "tres", "tribu", "tributo",
    "triste", "triunfo", "trompeta", "tronco", "tropa", "tubo", "tumor", "tunel", "turbio", "turismo",
    "ultimo", "unir", "uno", "universidad", "urgente", "usar", "uso", "util", "uvas", "vacio",
    "valiente", "valor", "vapor", "variable", "varios", "vecino", "vegetal", "veinte", "velocidad", "vender",
    "vengarse", "venir", "ventana", "ver", "verano", "verde", "verdad", "verdadero", "vestido", "vestir",
    "vez", "viaje", "vida", "vidrio", "viejo", "viento", "vigor", "villa", "vino", "violencia",
    "violin", "virgen", "virtud", "visible", "vision", "visita", "visitar", "vista", "vivir", "vivo",
    "volar", "volumen", "volver", "voto", "voz", "vuelta", "yegua", "yema", "yerno", "yoga",
    "yodo", "yogur", "zafiro", "zumo", "zurdo"
];

// NOTA: 'categoriasES' y 'phraseTemplates' se mantienen aquí por si decides reintroducir
// la lógica de "Generar frase con sentido" en el futuro, pero no se usan actualmente.
export const categoriasES = {
    articulos: ["el", "la", "los", "las", "un", "una", "unos", "unas"],
    pronombres: ["yo", "tú", "él", "ella", "nosotros", "vosotros", "ellos", "ellas"],
    sustantivos: [
        "agua", "aire", "casa", "perro", "gato", "libro", "mesa", "silla",
        "ciudad", "hombre", "mujer", "niño", "flor", "árbol", "sol", "luna",
        "tiempo", "vida", "mundo", "trabajo", "escuela", "familia", "amigo",
        "elefante", "montaña", "río", "estrella", "computadora", "teléfono",
        "jardín", "cielo", "nube", "canción", "noche", "día", "comida", "sueño",
        "viaje", "camino", "voz", "silencio", "puerta", "ventana", "color", "sonrisa"
    ],
    verbos: [
        "correr", "saltar", "dormir", "leer", "bailar", "comer", "beber", "cantar",
        "hablar", "escribir", "amar", "vivir", "pensar", "sentir", "querer", "hacer",
        "ver", "oír", "tocar", "jugar", "estudiar", "trabajar", "viajar", "aprender",
        "crecer", "soñar", "despertar", "volar", "navegar", "buscar", "encontrar", "crear",
        "construir", "imaginar", "recordar", "olvidar", "ayudar", "llegar", "partir"
    ],
    adjetivos: [
        "grande", "pequeño", "rojo", "azul", "feliz", "triste", "rápido", "lento",
        "bueno", "malo", "hermoso", "feo", "fuerte", "débil", "joven", "viejo",
        "nuevo", "antiguo", "alto", "bajo", "claro", "oscuro", "inteligente", "divertido",
        "interesante", "aburrido", "dulce", "amargo", "suave", "áspero", "limpio", "sucio"
    ],
    adverbios: [
        "lentamente", "rápidamente", "bien", "mal", "siempre", "nunca", "aquí", "allí",
        "hoy", "ayer", "mañana", "tarde", "pronto", "lejos", "cerca", "mucho", "poco", "muy",
        "demasiado", "quizás", "nunca", "aún", "casi", "solo", "también", "además"
    ],
    preposiciones: ["a", "con", "de", "en", "para", "por", "sobre", "sin", "entre", "hacia", "desde", "hasta", "contra", "según"],
    conjunciones: ["y", "o", "pero", "porque", "si", "que", "como", "cuando", "mientras", "aunque"]
};

export const phraseTemplates = [
    ["articulos", "sustantivos", "verbos", "articulos", "sustantivos"],
    ["pronombres", "verbos", "adverbios"],
    ["articulos", "sustantivos", "adjetivos", "verbos"],
    ["sustantivos", "verbos", "preposiciones", "articulos", "sustantivos"],
    ["verbos", "articulos", "sustantivos"],
    ["verbos", "adverbios"],
    ["articulos", "sustantivos", "y", "articulos", "sustantivos"],
    ["verbos", "conjunciones", "verbos"],
    ["articulos", "adjetivos", "sustantivos"],
    ["sustantivos", "adjetivos", "adjetivos"],
];